name: ğŸ—ï¸ PREBUILT_A11-5.4-LTS
on:
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:

jobs:

  build_atomx_sky_stock:
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ‘¨â€ğŸ”§ Setup build environment"
        run: curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh | bash -
      - name: "â³ Clone Repo, Sync & Build."
        run: repo init -u https://gitlab.com/xprateek/kernel_manifest -b common-android11-5.4-lts --depth=1 && repo sync && LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
      - name: "ğŸ“„ Generating Release Tag"
        id: tag
        run: echo "release_tag=xprateek/SOURCE_KERNEL_CICD_GKI_STOCK-$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT
      - name: "ğŸ—ƒï¸ Create Release"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: /home/runner/work/aosp_kernel_gki_builder/aosp_kernel_gki_builder/out/android12-5.10/dist/Image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repository: xprateek/aosp_kernel_gki_builder
          TOKEN: ${{ secrets.TOKEN }}

  build_atomx_sky_ksu:
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ‘¨â€ğŸ”§ Setup build environment"
        run: curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh | bash -
      - name: "â³ Clone Repo, Sync & Build."
        run: repo init -u https://gitlab.com/xprateek/kernel_manifest -b common-android11-5.4-lts --depth=1 && repo sync && cd common && curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash - && cd ../ && LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh 
      - name: "ğŸ“„ Generating Release Tag"
        id: tag
        run: echo "release_tag=xprateek/SOURCE_KERNEL_CICD_GKI_KSU-$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT
      - name: "ğŸ—ƒï¸ Create Release"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: /home/runner/work/aosp_kernel_gki_builder/aosp_kernel_gki_builder/out/android12-5.10/dist/Image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repository: xprateek/aosp_kernel_gki_builder
          TOKEN: ${{ secrets.TOKEN }}
